#!/bin/bash

set -e

# Configuration
# following configuration parameters required:
# DB_BACKUP_AWS_ACCESS_KEY_ID=
# DB_BACKUP_AWS_SECRET_ACCESS_KEY=
# DB_BACKUP_AWS_DEFAULT_REGION=
# DB_BACKUP_TARGET_BUCKET=
# DB_BACKUP_ROOT=
# DB_BACKUP_BASE_NAME=

ROOT_DIR="$( git rev-parse --show-toplevel 2>/dev/null || echo '')"

if [[ -z $ROOT_DIR ]]; then
  TMP_DIR=$ROOT_DIR/tmp
else
  TMP_DIR=/tmp
fi

if [[ -z "$RAILS_ENV" ]]; then
  RAILS_ENV=development
fi

if [ "$RAILS_ENV" != "production" ]; then
  if [[ -f ${ROOT_DIR}/.env ]]; then
    . ${ROOT_DIR}/.env
  fi

  if [[ -f ${ROOT_DIR}/.env.${RAILS_ENV} ]]; then
    . ${ROOT_DIR}/.env.${RAILS_ENV}
  fi

  if [[ -f ${ROOT_DIR}/.env.db_tools ]]; then
    . ${ROOT_DIR}/.env.db_tools
  fi
fi

export AWS_ACCESS_KEY_ID=${DB_BACKUP_AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${DB_BACKUP_AWS_SECRET_ACCESS_KEY}
export AWS_DEFAULT_REGION=${DB_BACKUP_AWS_DEFAULT_REGION}


while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
    -bn|--base-name)
      BACKUP_BASE_NAME=$2
      shift 2
      ;;
    -bn=*|--base-name=*)
      BACKUP_BASE_NAME="${1#*=}"
      shift 1
      ;;

    -npx|--name-prefix)
      BACKUP_FILE_PREFIX=$2
      shift 2
      ;;
    -npx=*|--name-prefix=*)
      BACKUP_FILE_PREFIX="${1#*=}"
      shift 1
      ;;

    -nsx|--name-suffix)
      BACKUP_FILE_SUFFIX=$2
      shift 2
      ;;
    -nsx=*|--name-suffix=*)
      BACKUP_FILE_SUFFIX="${1#*=}"
      shift 1
      ;;

    -db|--database-url)
      DATABASE_URL=$2
      shift 2
      ;;
    -db=*|--database-url=*)
      DATABASE_URL="${1#*=}"
      shift 1
      ;;

    --backup-root)
      BACKUP_ROOT=$2
      shift 2
      ;;
    --backup-root=*)
      BACKUP_ROOT="${1#*=}"
      shift 1
      ;;

    --backup-dir)
      BACKUP_DIR=$2
      shift 2
      ;;
    --backup-dir=*)
      BACKUP_DIR="${1#*=}"
      shift 1
      ;;

    --backup-file-name)
      BACKUP_FILE_NAME=$2
      shift 2
      ;;
    --backup-file-name=*)
      BACKUP_FILE_NAME="${1#*=}"
      shift 1
      ;;

    --backup-remote-file-path)
      REMOTE_FILE_PATH=$2
      shift 2
      ;;
    --backup-remote-file-path=*)
      REMOTE_FILE_PATH="${1#*=}"
      shift 1
      ;;
    *)
      shift
      ;;
  esac
done

if [[ -z "$BACKUP_BASE_NAME" ]]; then
  BACKUP_BASE_NAME=$DB_BACKUP_BASE_NAME
fi

if [[ -z "$BACKUP_ROOT" ]]; then
  BACKUP_ROOT=${DB_BACKUP_ROOT}
fi

if [[ -z "$BACKUP_DIR" ]]; then
  BACKUP_DIR=$(date +"%Y/%Y-%m/%Y-%m-%d" --utc)
fi

if [[ -z "$BACKUP_FILE_NAME" ]]; then
  BACKUP_FILE_NAME=$(
    date +"${BACKUP_FILE_PREFIX}${BACKUP_BASE_NAME}_%Y_%m_%d__%H_%M_%S${BACKUP_FILE_SUFFIX}.tar" --utc
  )
fi

if [[ -z "$REMOTE_FILE_PATH" ]]; then
  REMOTE_FILE_PATH="${BACKUP_ROOT}/${BACKUP_DIR}/${BACKUP_FILE_NAME}"
fi

S3_FILE_PATH="s3://${DB_BACKUP_TARGET_BUCKET}/${REMOTE_FILE_PATH}"

aws configure set default.s3.multipart_chunksize 50MB

BACKUP_TARGET_DIR=${TMP_DIR}/${BACKUP_FILE_NAME}

echo "Local backup stored at ${BACKUP_TARGET_DIR}"

mkdir ${BACKUP_TARGET_DIR}

pg_dump -j$(nproc) --format=directory -Z 5 -d "${DATABASE_URL}" -f ${BACKUP_TARGET_DIR}
(cd ${BACKUP_TARGET_DIR} && md5sum --tag -b * > ./backup_manifest.md5)

tar cf - -C ${BACKUP_TARGET_DIR} . | aws s3 cp - "${S3_FILE_PATH}"
aws s3 cp "${BACKUP_TARGET_DIR}/backup_manifest.md5" "${S3_FILE_PATH}.md5"

rm -r ${BACKUP_TARGET_DIR}

echo "Backed successfully up to: ${REMOTE_FILE_PATH}"