#!/usr/bin/env bash

## Peform setup
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. ${SCRIPT_DIR}/db_backup_setup

## Process params
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
    -rf|---remote-file)
      REMOTE_FILE=$2
      shift 2
      ;;
    -rf=*|---remote-file=*)
      REMOTE_FILE="${1#*=}"
      shift 1
      ;;
    *)
      shift
      ;;
  esac
done

if [[ -z "$REMOTE_FILE" ]]; then
  REMOTE_FILE=$(db_ls_backups | grep -v next | tail -n 1 | awk '{ print $1; }')
fi

aws s3 presign \
  s3://${DB_BACKUP_TARGET_BUCKET}/${REMOTE_FILE} \
  --expires-in 300
