#!/usr/bin/env bash

## Peform setup
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. ${SCRIPT_DIR}/db_backup_setup

## Process params
LEFT_BOUNDARY="00:00 yesterday UTC"
RIGHT_BOUNDARY="00:00 tomorrow UTC"

NEXT_PAGE_TOKEN=

while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
    -p|--prefix)
      BACKUP_PREFIX=$2
      shift 2
      ;;
    -p=*|--prefix=*)
      BACKUP_PREFIX="${1#*=}"
      shift 1
      ;;

    # -l|--left-bound)
    #   LEFT_BOUNDARY=$2
    #   shift 2
    #   ;;
    # -l=*|--left-bound=*)
    #   LEFT_BOUNDARY="${1#*=}"
    #   shift 1
    #   ;;

    # -r|--right-boundary)
    #   RIGHT_BOUNDARY=$2
    #   shift 2
    #   ;;
    # -r=*|--right-boundary=*)
    #   RIGHT_BOUNDARY="${1#*=}"
    #   shift 1
    #   ;;

    -d|--day)
      DAY="$2"
      LEFT_BOUNDARY="$DAY"
      RIGHT_BOUNDARY="$DAY + 1 day"
      shift 2
      ;;
    -d=*|--day=*)
      DAY="${1#*=}"
      LEFT_BOUNDARY="$DAY"
      RIGHT_BOUNDARY="$DAY + 1 day"
      shift 1
      ;;

    -np|--next-page)
      NEXT_PAGE_TOKEN="$2"
      shift 2
      ;;
    -np=*|--next-page=*)
      NEXT_PAGE_TOKEN="${1#*=}"
      shift 1
      ;;
    --output=*)
      OUTPUT_FORMAT="${1#*=}"
      shift 1
      ;;
    *)
      shift
      ;;
  esac
done

# LEFT_BOUNDARY=$(date +'%Y-%m-%d' --utc --date="${LEFT_BOUNDARY}")
# RIGHT_BOUNDARY=$(date +'%Y-%m-%d' --utc --date="${RIGHT_BOUNDARY}")

BACKUP_PREFIX=$(echo ${BACKUP_PREFIX} | sed -r 's/\/$//')
if [[ -n "${BACKUP_PREFIX}" ]]; then
  BACKUP_PREFIX=${BACKUP_PREFIX}/
fi

if [[ ! -z "$NEXT_PAGE_TOKEN" ]]; then
  NEXT_PAGE="--starting-token=$NEXT_PAGE_TOKEN"
else
  NEXT_PAGE=""
fi

if [[ $OUTPUT_FORMAT == "json" ]]; then
  aws s3api list-objects-v2 \
    --output=$OUTPUT_FORMAT \
    --bucket=${DB_BACKUP_TARGET_BUCKET} \
    --prefix=${BACKUP_PREFIX} \
    --delimiter=/ \
    --max-items=500
else
  aws s3 ls \
    --human-readable \
    s3://${DB_BACKUP_TARGET_BUCKET}/${BACKUP_PREFIX} \
    | awk "{ \$NF=\"${BACKUP_PREFIX}\"\$NF; print \$0 }"
fi


# aws s3api list-objects-v2 --bucket=${DB_BACKUP_TARGET_BUCKET} \
#   --prefix=${BACKUP_PREFIX} \
#   --max-items=500 \
#   $NEXT_PAGE \
#   --query="{ Contents: Contents, NextToken: NextToken }" \
#   | jq -c -r "(.Contents | map(.Key + \" \" + (.Size/1024/1024|floor|tostring)+\"M\") | join(\"\n\")) + \"\nnext \" + .NextToken" \
#   | grep -v -E '^next\s+$'