#!/usr/bin/env bash
set -e

## Peform setup
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. ${SCRIPT_DIR}/lib/uri_tools.bash

REST_ARGS=()
while [[ $# -gt 0 ]];
do
  key="$1"

  case $key in
    --pass)
      CONNECTION_URL_KEY=$2
      shift 2
      ;;
    --pass=*)
      CONNECTION_URL_KEY="${1#*=}"
      shift 1
      ;;
    # --)
      # shift 1
      # Rest args should be passed directly to psql
      # break
      # ;;
    *)
      REST_ARGS+=("$1")
      shift
      ;;
  esac
done

DB_URL=$(store_password_to_pgpass "$(pass $CONNECTION_URL_KEY)")

psql --dbname="$DB_URL" ${REST_ARGS[@]}

clean_pgpass "$DB_URL"